export const roleConstant = {
  SECURITY : 1,
  SUPER_ADMIN : 2,
  REQUESTER : 3,
  MANAGER : 4,
  TRAFFIC : 5,
  OPR : 6,
  WA_TEAM : 7,
  BSA : 8,
}

export const reqStatusConstant = {
  DRAFT_REQUESTER : 1,
  ON_PROGRESS_MANAGER : 2,
  REQUEST_CANCEL : 3,
  REJECTED_MANAGER : 4,
  CAMPAIGN_CANCELLED : 5,
  ON_PROGRESS_TRAFFIC : 6,
  REJECTED_TRAFFIC : 7,
  ON_PROGRESS_OPR : 8,
  ON_PROGRESS_SPV : 9,
  REJECTED_SPV : 10,
  ON_PROGRESS_WA_TEAM : 11,
  REJECTED_WA_TEAM : 12,
  ON_PROGRESS_META : 13,
  APPROVED_META : 14,
  REJECTED_META : 15,
  DRAFT_OPR : 16,
}




